config/routes.rb
Rails.application.routes.draw do

  get 'house_photos/create'

  get 'house_photos/edit'

  devise_for :users

  resources :houses
  resources :feedbacks
  resources :searches

  get 'staticpage/index'
  get 'staticpage/contacts'

  match 'feedbacks/:id/valid', :to => 'feedbacks#public_update', :as => 'feedback_val', :via => :post

  root "staticpage#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :houses
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/models/house.rb
class House < ActiveRecord::Base

  belongs_to :category

  has_many :searches

  has_many :house_photos

  accepts_nested_attributes_for :house_photos, allow_destroy: true, reject_if: proc { |t| t['house_photo'].blank? }

end

app/models/house_photo.rb
class HousePhoto < ActiveRecord::Base

  belongs_to :house

  has_attached_file :image, styles: {}, default_url: "missing.png"
  validates_attachment_presence :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/search.rb
class Search < ActiveRecord::Base

  def search_houses
    houses = House.all

    houses = houses.where(["street ILIKE ?", "%#{street}%"]) unless street.blank?
    houses = houses.where(["price >= ?", min_price]) unless min_price.blank?
    houses = houses.where(["price <= ?", max_price]) unless max_price.blank?
    houses = houses.where(["category_id = ?", realty_typ]) unless realty_typ.blank?
    houses = houses.where(["floor >= ?", min_floor_quantity]) unless min_floor.blank?
    houses = houses.where(["floor <= ?", max_floor_quantity]) unless max_floor.blank?
    houses = houses.where(["floor_quantity >= ?", min_floor_quantity]) unless min_floor_quantity.blank?
    houses = houses.where(["floor_quantity <= ?", max_floor_quantity]) unless max_floor_quantity.blank?
    houses = houses.where(["room_quantity >= ?", min_room_quantity]) unless min_room_quantity.blank?
    houses = houses.where(["room_quantity <= ?", max_room_quantity]) unless max_room_quantity.blank?

    return houses
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  before_action :find_fb, only: [:show, :update, :destroy, :edit]

  def index
  end

  def new
    @feedback = Feedback.new
    if user_signed_in?
      @fb = Feedback.find_by_sql("SELECT * FROM feedbacks WHERE public=false")
    else
      @fb = Feedback.find_by_sql("SELECT * FROM feedbacks WHERE public=true")
    end
  end

  def create
    @feedback = Feedback.new(fb_params)
    if @feedback.save
      redirect_to root_path
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def public_update
    @feedback = Feedback.find(params[:id])
    @feedback.update_attribute(:public, true)
    redirect_to new_feedback_path
  end
  private

  def fb_params
    params.require(:feedback).permit(:name, :content, :public)
  end

  def find_fb
    @feedback = Feedback.find(params[:id])
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

  before_action :find_house, only: [:show, :edit, :destroy, :update]
  before_action :authenticate_user!, only: [:new, :create, :destroy, :update, :edit]

  def index
    @houses = House.all
  end

  def new
    @house = House.new
    @house.house_photos.build
  end

  def show
    @photos = @house.house_photos
  end

  def create
    @house = House.new(house_params)

    if @house.save
      if params[:images]
        params[:images].each { |image| @house.house_photos.create(image: image) }
      end
      redirect_to @house
    else
      render 'new'
    end
  end

  def destroy
    @house.destroy
    redirect_to root_path
  end

  def update
    if @house.update(house_params)
      if params[:images]
        params[:images].each { |image| @house.house_photos.create(image: image) }
      end
      redirect_to @house
    else
      render "edit"
    end
  end

  def edit
    @house.house_photos.build
  end

  private

  def house_params
    params.require(:house).permit(:title, :description,
    :category_id, :district, :street, :price, :room_quantity,
    :floor, :floor_quantity, :image, :square_all, :square_kitchen,
    :square_live, house_photos_attributes: [:image, :_destroy] )
  end

  def find_house
    @house = House.find(params[:id])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @search = Search.new
    @districts = House.uniq.pluck(:district)
  end

  def show
    @search = Search.find(params[:id])
  end

  def create
    @search = Search.new search_params
    if @search.save
      redirect_to @search
    else
      render 'new'
    end
  end

  private

  def search_params
    params.require(:search).permit(:realty_typ, :street, :district, :min_price,
    :max_price, :min_room_quantity, :max_room_quantity, :min_floor, :max_floor,
    :min_floor_quantity, :max_floor_quantity)
  end
end

app/controllers/staticpage_controller.rb
class StaticpageController < ApplicationController

  def index
  end

  def contacts
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/house_photos_helper.rb
module HousePhotosHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/staticpage_helper.rb
module StaticpageHelper
end

app/views/feedbacks/_fb_form.html.haml
.feed
  .newFeedback
    %h2
      Оставить свой отзыв
    = simple_form_for(@feedback, html: { class: 'form-horizontal' }) do |f|
      = f.input :name, label: "Имя"
      = f.input :content, label: "Отзыв"
      %br/
      = f.button :submit,"Оставить" , class: "btn btn-success"

app/views/feedbacks/new.html.haml
= provide(:title, "Отзывы")
= render 'fb_form'

%h2 Отзывы пользователей:
.feedBacks
  .feedBack.row
    - @fb.each do |fb|
      .feedBack
        .col-xs-10.col-sm-10.col-md-10.col-lg-10
          %h3= fb.name
          %h4= fb.content
        - if user_signed_in?
          .col-xs-2.col-sm-2.col-md-2.col-lg-2.btn-group
            = link_to feedback_valid_path(fb), method: :post do
              %i.fa.fa-thumbs-up.fa-2x
            = link_to feedback_path(fb), method: :delete do
              %i.fa.fa-thumbs-down.fa-2x

app/views/houses/_form.html.haml
= simple_form_for(@house, html: { class: 'form-horizontal', multipart: true }) do |f|
  = f.input :title, label: "Заглавие объявления"
  = f.input :description, label: "Описание"
  = f.collection_select :category_id, Category.all, :id, :name, {prompt: "Выберите тип недвижимости"}
  = f.input :square_all, label: "Общая площадь"
  = f.input :square_live, label: "Жилая площадь"
  = f.input :square_kitchen, label: "Площадь кухни"
  = f.input :district, label: "Район"
  = f.input :street, label: "Улица"
  = f.input :price, label: "Цена"
  = f.input :room_quantity, label: "Количество комнат"
  = f.input :floor, label: "Этаж"
  = f.input :floor_quantity, label: "Этажность"
  = f.label "Фото", class: 'control-label'
  = file_field_tag "images[]", type: :file, multiple: true
  %br/
  =f.button :submit, "Добавить", class: "btn btn-success"

app/views/houses/edit.html.erb
<h1>Houses#edit</h1>
<p>Find me in app/views/houses/edit.html.erb</p>

app/views/houses/edit.html.haml
= provide(:title, "Главная")
%h1 Edit House

= render "form"

= link_to "Back", root_path

app/views/houses/index.html.haml
= provide(:title, "Недвижимость")

- if user_signed_in?
  = link_to " Добавить", new_house_path, class: "btn btn-success fa fa-plus-square"
.results
  - @houses.each do |house|
    .row.result
      .col-xs-3.col-sm-3.col-md-3.col-lg-3{:style => "text-align: center"}
        - if house.house_photos.first.present?
          = link_to image_tag(house.house_photos.first.image.url), house
      .col-xs-7.col-sm-7.col-md-7.col-lg-7
        %h3
          = link_to house.district + ", " + house.street, house
        %h4
          = "Этаж: "+house.floor.to_s+"/"+house.floor_quantity.to_s+", Площадь: " + house.square_all.to_s + "/"+ house.square_live.to_s + "/" + house.square_kitchen.to_s + ", Комнат: " + house.room_quantity.to_s + ", " + house.category.name.downcase
      .col-xs-2.col-sm-2.col-md-2.col-lg-2.cost
        %h2
          = house.price.to_s
          %i.fa.fa-usd{"aria-hidden" => "true"}

app/views/houses/new.html.haml
= provide(:title, "Добавить недвижимость")
%h1 Добавить недвижимость

= render "form"

= link_to "На главную", root_path

app/views/houses/show.html.haml
= provide(:title, "Недвижимость")

.gallery.col-xs-12.col-sm-12.col-md-8.col-lg-8{:align => "center"}
  - unless @photos.empty?
    .preview{:align => "center"}
      = image_tag(@photos[0].image.url, name: 'preview')
    - i = 0
    - size = @photos.size
    .thumbnails
      - while i < size
        = image_tag(@photos[i].image.url, onClick: "preview.src=img#{i}.src".html_safe, name: "img#{i}")
        - i += 1
.col-xs-12.col-sm-12.col-md-4.col-lg-4
  %h2
    %span= @house.title
    %span= @house.price.to_s
    %i.fa.fa-usd{"aria-hidden" => "true"}
  .btn-group{:role => "group"}
    = link_to "На главную", root_path, class: "btn btn-default fa fa-home"
    - if user_signed_in?
      = link_to " Редактировать", edit_house_path, class: "btn btn-primary fa fa-pencil-square-o"
      = link_to " Удалить", house_path(@house), method: :delete, class: "btn btn-danger fa fa-trash"
.dataOfProperty
  %h3
    %span= @house.street + ", " + @house.floor.to_s + "/" + @house.floor_quantity.to_s + " Этаж, " + @house.square_all.to_s + "/"+ @house.square_live.to_s + "/" + @house.square_kitchen.to_s + " площадь."
    %h4= simple_format(@house.description)

app/views/layouts/application.html.haml
!!!
%html
%head
  %title
    = yield(:title)
    | Empire of Apartments
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %div.menu.row
    %div.col-xs-12.col-sm-12.col-md-12.col-lg-12.logo
      = image_tag("YBirJaX3haQ.jpg")
    %div.col-xs-12.col-sm-12.col-md-12.col-lg-12
      %ul.nav.nav-pills.nav-justified
        %li
          = link_to "Главная", root_path
        %li
          = link_to "Недвижимость", houses_path
        %li
          = link_to "Контакты", staticpage_contacts_path
        %li
          = link_to "Отзывы", new_feedback_path
  .content
    .row
      = yield
%footer
  - if user_signed_in?
    = link_to "Выйти", destroy_user_session_path, method: :delete
  - else
    = link_to "Войти", new_user_session_path
  %div.row
    %div.col-xs-6.col-sm-6.col-md-6.col-lg-6
      %h2 ©All rights reserved
    %div.col-xs-6.col-sm-6.col-md-6.col-lg-6
      %h2.year 2016

app/views/searches/new.html.haml
= form_for @search do |f|
  %p
    = f.label "Тип недвижимости:"
    %br/
    = f.collection_select :realty_typ, Category.all, :id, :name, include_blank: true
  %p
    = f.label "Район"
    %br/
    = f.select :district, options_for_select(@districts), include_blank: true
  %p
    = f.label "Улица"
    %br/
    = f.text_field :street
  %p
    = f.label "Цена: "
    %br/
    = f.text_field :min_price, size: 7
    = f.text_field :max_price, size: 7
  %p
    = f.label "Количество комнат: "
    %br/
    = f.text_field :min_room_quantity, size: 7
    = f.text_field :max_room_quantity, size: 7
  %p
    = f.label "Этаж: "
    %br/
    = f.text_field :min_floor, size: 7
    = f.text_field :max_floor, size: 7
  %p
    = f.label "Этажность: "
    %br/
    = f.text_field :min_floor_quantity, size: 7
    = f.text_field :max_floor_quantity, size: 7
  %p
    = f.submit "Поиск"

app/views/searches/show.html.haml
%h1
  = "Результаты поиска"
= link_to "Назад", new_search_path

- if @search.search_houses.empty?
  = "Не найдено ни одной недвижимости"
- else
  = @search.search_houses.each do |house|
    .row.result
      .col-xs-3.col-sm-3.col-md-3.col-lg-3{:style => "text-align: center"}
        = link_to image_tag(house.image.url), house
      .col-xs-7.col-sm-7.col-md-7.col-lg-7
        %h3
          = link_to house.district + ", " + house.street, house
        %h4
          = "Этаж: "+house.floor.to_s+"/"+house.floor_quantity.to_s+", Площадь: " + house.square + ", Комнат: " + house.room_quantity.to_s + ", " + house.category.name.downcase
      .col-xs-2.col-sm-2.col-md-2.col-lg-2.cost
        %h2
          = house.price.to_s
          %i.fa.fa-usd{"aria-hidden" => "true"}

app/views/staticpage/contacts.html.haml
= provide(:title, "Контакты")
%div.content.row{:style => "margin: 0;"}
  .col-xs-12.col-sm-12.col-md-6.col-lg-6{:style => "text-align: center"}
    %a{:href => "https://maps.yandex.ua/?um=constructor:8MtSObNo-TbdrYzZBQks2IYSX3nWAmr3&source=constructor", :target => "_blank"}
      %img.map{:alt => "", :src => "https://api-maps.yandex.ru/services/constructor/1.0/static/?sid=8MtSObNo-TbdrYzZBQks2IYSX3nWAmr3&width=600&height=450&lang=uk_UA&sourceType=constructor", :style => "border: 0;"}/
  .col-xs-12.col-sm-12.col-md-6.col-lg-6.contacts
    %h2.address
      Мы находимся по адресу:
      %br/
      %br/
      %i.fa.fa-map-marker{"aria-hidden" => "true"}
      Украина, г.Одесса, ул.Гайдара, 34
    %br/
    %h3.numbers
      Контактные номера:
      %br/
      %br/
      %i.fa.fa-phone{"aria-hidden" => "true"}
      (048) 788-04-21
      %br/
      %br/
      %i.fa.fa-phone{"aria-hidden" => "true"}
      (068) 310-36-38
      %br/
      %br/
      Отдел продаж новостроя:
      %br/
      %br/
      %i.fa.fa-phone{"aria-hidden" => "true"}
      (048) 788-04-23
      %br/
      %br/
      %i.fa.fa-phone{"aria-hidden" => "true"}
      (068) 310-36-39
      %h3
        %h3.vk Мы в социальных сетях:
        %h3#vk.vk
          %a{:href => "https://vk.com/imperia_kvartir_odessa"}
            %i.fa.fa-vk.fa-2x{"aria-hidden" => "true"}

app/views/staticpage/index.html.haml
= provide(:title, "Главная")
%div.row
  %div.col-xs-12.col-sm-12.col-md-4.col-lg-4
    = image_tag("main.jpg")
  %div.col-xs-12.col-sm-12.col-md-8.col-lg-8
    %div.text
      %h2
        %center
          ООО «Региональный центр недвижимости»
      %p
        Агентство недвижимости «Империя квартир» - это новый надёжный партнёр на рынке недвижимости, который предоставит Вам полный спектр профессиональных услуг с совершенно новым подходом в этой области.
      %p
        В Агентстве недвижимости «Империя квартир» работает опытный молодой коллектив, который готов предоставить Вам качественную бесплатную консультацию по интересующему Вас вопросу в области недвижимости.
      %p
        Агентство недвижимости «Империя квартир» сотрудничает только с проверенными, надёжными строительными компаниями. Специалисты нашей компании предоставит Вам качественные услуги по приобретению объектов в новостроях от ведущих строительных компаний города, а так же предоставит полную и расширенную информацию о состоянии рынка недвижимости на данный момент и в перспективе. Квалифицированные агенты помогут Вам приобрести или продать квартиру (или любой другой вид недвижимости) по Одессе и Одесской области, а так же апартаменты, виллы, дома, коттеджи, участки за рубежом.
      %h3
        Принципы  работы нашей компании:
      %ul{:type => "circle"}
        %li
          Прозрачность и Честность отношений;
        %li
          Высочайший Профессионализм и Качество работы;
        %li
          Конфиденциальность;
        %li
          Мы ценим доверие Клиентов;
        %li
          Мы уважаем интересы Партнёров;
        %li
          Мы используем честные методы конкурентной работы;
        %li
          Мы создаем эффективный, цивилизованный бизнес;
        %li
          Нас рекомендуют друзья, наши клиенты и их друзья;
        %li
          Мы ценим Ваше время, силы и деньги;
        %li
          С нами купить просто – жить легко.
      %p
        Мы всегда рады видеть Вас по адресу: г. Одесса, ул. Гайдара 34, где Вас ждёт дружный коллектив профессионалов, а также чашечка кофе и хорошее настроение.